name: Build & Deploy Angular App to Firebase

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v3

      - name: üîß Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: üì¶ Install dependencies
        run: npm install

      - name: üìÇ Ensure environments directory exists
        run: mkdir -p src/environments

      - name: üìù Generate environment.prod.ts
        run: node scripts/generate-env.js
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: üõ†Ô∏è Build Angular app
        run: npm run build -- --configuration production

      - name: üöÄ Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: üöÄ Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLEZIONI_SAS }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
